<?php

$schema =  Array(
    'No' => __('api_merlion_info.no'),
    'Name' => __('api_merlion_info.name'),
    'Brand' => __('api_merlion_info.Brand'),
    'Vendor_part' => __('api_merlion_info.Vendor_part'),
    'Size' => __('api_merlion_info.Size'),
    'EOL' => __('api_merlion_info.EOL'),
    'Warranty' => __('api_merlion_info.Warranty'),
    'Weight' => __('api_merlion_info.Weight'),
    'Volume' => __('api_merlion_info.volume'),
    'Min_Packaged' => __('api_merlion_info.Min_Packaged'),
    'GroupName1' => __('api_merlion_info.GroupName1'),
    'GroupName2' => __('api_merlion_info.GroupName2'),
    'GroupName3' => __('api_merlion_info.GroupName3'),
    'GroupCode1' => __('api_merlion_info.GroupCode1'),
    'GroupCode2' => __('api_merlion_info.GroupCode2'),
    'GroupCode3' => __('api_merlion_info.GroupCode3'),
    'IsBundle' => __('api_merlion_info.IsBundle'),
    'ActionDesc' => __('api_merlion_info.ActionDesc'),
    'ActionWWW' => __('api_merlion_info.ActionWWW'),
    'Last_time_modified' => __('api_merlion_info.Last_time_modified'),
    'PriceClient' => __('api_merlion_info.PriceClient'),
    'PriceClient_RG' => __('api_merlion_info.PriceClient_RG'),
    'PriceClient_MSK' => __('api_merlion_info.PriceClient_MSK'),
    'AvailableClient' => __('api_merlion_info.AvailableClient'),
    'AvailableClient_RG' => __('api_merlion_info.AvailableClient_RG'),
    'AvailableClient_MSK' => __('api_merlion_info.AvailableClient_MSK'),
    'AvailableExpected' => __('api_merlion_info.AvailableExpected'),
    'AvailableExpectedNext' => __('api_merlion_info.AvailableExpectedNext'),
    'DateExpectedNext' => __('api_merlion_info.DateExpectedNext'),
    'RRP' => __('api_merlion_info.RRP'),
    'RRP_Date' => __('api_merlion_info.RRP_Date'),
    'PriceClientRUB' => __('api_merlion_info.PriceClientRUB'),
    'PriceClientRUB_RG' => __('api_merlion_info.PriceClientRUB_RG'),
    'PriceClientRUB_MSK' => __('api_merlion_info.PriceClientRUB_MSK'),
    'Online_Reserve' => __('api_merlion_info.Online_Reserve'),
    'ReserveCost' => __('api_merlion_info.ReserveCost'),
    'VAT' => __('api_merlion_info.VAT'),
    'Sales_Limit_Type' => __('api_merlion_info.Sales_Limit_Type'),
);

return $schema;      